package nl.ansuz.android.steam.dota.util;

import nl.ansuz.android.steam.dota.vo.BuildItemVO;

/**
 * Auto-generated Hero build item list.
 * 
 * This class gets generated by passing the DotA game file 
 * "scripts/npc/items.txt" that can be extracted from 
 * "<path to steam>/Steam/steamapps/common/dota 2 beta/dota/pak01_dir.vpk"
 * 
 * Use tools/itemparser/BuildItemsParser.py to generate.
 * 
 * @author Wijnand
 */
public class HeroBuildItemList {

	private BuildItemVO[] itemList;
	
	/**
	 * CONSTRUCTOR
	 */
	public HeroBuildItemList() {
		init();
	}

	/**
	 * Initializes this class.
	 */
	private void init() {
		createItemList();
	}

	/**
	 * Constructs the Hero build item list.
	 */
	private void createItemList() {
		itemList = new BuildItemVO[@@injectItemCount@@];
@@injectItems@@
	}
	
	public BuildItemVO getItemById(int id) {
		BuildItemVO item = null;
		
		if(id < itemList.length) {
			item = itemList[id];
		}
		
		return item;
	}
}
