package nl.ansuz.android.steam.dota.util;

import nl.ansuz.android.steam.dota.vo.BuildItemVO;
import nl.ansuz.android.steam.dota.vo.heroes.AbilityVO;

/**
 * Auto-generated Hero build item list.
 * 
 * This class gets generated by passing the DotA game file 
 * "scripts/npc/items.txt" that can be extracted from 
 * "<path to steam>/Steam/steamapps/common/dota 2 beta/dota/pak01_dir.vpk"
 * 
 * Use tools/itemparser/BuildItemsParser.py to generate.
 * 
 * @author Wijnand
 */
public class HeroBuildItemList {

	private BuildItemVO[] itemList;
	
	/**
	 * CONSTRUCTOR
	 */
	public HeroBuildItemList() {
		init();
	}

	/**
	 * Initializes this class.
	 */
	private void init() {
		createItemList();
	}

	/**
	 * Constructs the Hero build item list.
	 */
	private void createItemList() {
		itemList = new BuildItemVO[241];
		itemList[1] = new BuildItemVO(1, "Blink dagger", "item_blink", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DIRECTIONAL.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES.behaviourValue, new int[]{0}, 0.0, new double[]{12.0}, new int[]{75}, 2150, new String[]{"teleport"}, "component", true, new String[]{"npc_dota_hero_vengefulspirit", "npc_dota_hero_pudge"});
		itemList[2] = new BuildItemVO(2, "Blades of Attack", "item_blades_of_attack", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"damage", "tutorial"}, "component", true, null);
		itemList[3] = new BuildItemVO(3, "Broadsword", "item_broadsword", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1200, new String[]{"damage"}, "component", false, null);
		itemList[4] = new BuildItemVO(4, "Chainmail", "item_chainmail", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 550, new String[]{"armor"}, "component", true, null);
		itemList[5] = new BuildItemVO(5, "Claymore", "item_claymore", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1400, new String[]{"damage"}, "component", false, null);
		itemList[6] = new BuildItemVO(6, "Helm of Iron Will", "item_helm_of_iron_will", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 950, new String[]{"armor", "regen_health"}, "component", true, null);
		itemList[7] = new BuildItemVO(7, "Javelin", "item_javelin", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1500, new String[]{"damage"}, "component", false, null);
		itemList[8] = new BuildItemVO(8, "Mithril Hammer", "item_mithril_hammer", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1600, new String[]{"damage"}, "component", false, null);
		itemList[9] = new BuildItemVO(9, "Platemail", "item_platemail", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1400, new String[]{"armor"}, "component", false, null);
		itemList[10] = new BuildItemVO(10, "Quarterstaff", "item_quarterstaff", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 900, new String[]{"damage", "attack_speed"}, "component", true, null);
		itemList[11] = new BuildItemVO(11, "Quelling Blade", "item_quelling_blade", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{350}, 0.0, new double[]{5.0}, new int[]{0}, 225, new String[]{"damage"}, "component", true, null);
		itemList[12] = new BuildItemVO(12, "Ring of Protection", "item_ring_of_protection", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 175, new String[]{"armor"}, "component", false, null);
		itemList[182] = new BuildItemVO(182, "Stout Shield", "item_stout_shield", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 250, new String[]{"block"}, "component", true, null);
		itemList[13] = new BuildItemVO(13, "Gauntlets", "item_gauntlets", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 150, new String[]{"str"}, "component", false, null);
		itemList[14] = new BuildItemVO(14, "Slippers", "item_slippers", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 150, new String[]{"agi"}, "component", true, null);
		itemList[15] = new BuildItemVO(15, "Mantle", "item_mantle", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 150, new String[]{"int"}, "component", false, null);
		itemList[16] = new BuildItemVO(16, "Branches", "item_branches", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 53, new String[]{"agi", "int", "str"}, "component", false, null);
		itemList[17] = new BuildItemVO(17, "Belt of Strength", "item_belt_of_strength", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"str"}, "component", true, null);
		itemList[18] = new BuildItemVO(18, "Boots of Elves", "item_boots_of_elves", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"agi"}, "component", true, null);
		itemList[19] = new BuildItemVO(19, "Robe", "item_robe", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"int"}, "component", true, null);
		itemList[20] = new BuildItemVO(20, "Circlet", "item_circlet", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 185, new String[]{"agi", "int", "str"}, "component", false, null);
		itemList[21] = new BuildItemVO(21, "Ogre Axe", "item_ogre_axe", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1000, new String[]{"str"}, "component", false, null);
		itemList[22] = new BuildItemVO(22, "Blade of Alacrity", "item_blade_of_alacrity", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1000, new String[]{"agi"}, "component", false, null);
		itemList[23] = new BuildItemVO(23, "Staff of Wizardry", "item_staff_of_wizardry", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1000, new String[]{"int"}, "component", false, null);
		itemList[24] = new BuildItemVO(24, "Ultimate Orb", "item_ultimate_orb", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2100, new String[]{"agi", "int", "str"}, "component", true, null);
		itemList[25] = new BuildItemVO(25, "Gloves", "item_gloves", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 500, new String[]{"attack_speed"}, "component", true, null);
		itemList[26] = new BuildItemVO(26, "Lifesteal", "item_lifesteal", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 900, new String[]{"unique"}, "component", true, null);
		itemList[27] = new BuildItemVO(27, "Ring of Regen", "item_ring_of_regen", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 350, new String[]{"regen_health"}, "component", true, null);
		itemList[28] = new BuildItemVO(28, "Sobi Mask", "item_sobi_mask", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 325, new String[]{"regen_mana"}, "component", true, null);
		itemList[29] = new BuildItemVO(29, "Boots", "item_boots", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"move_speed"}, "component", true, null);
		itemList[30] = new BuildItemVO(30, "Gem", "item_gem", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 850, new String[]{"see_invis"}, "component", false, null);
		itemList[31] = new BuildItemVO(31, "Cloak", "item_cloak", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 550, new String[]{"magic_resist"}, "component", true, null);
		itemList[32] = new BuildItemVO(32, "Talisman of Evasion", "item_talisman_of_evasion", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1800, new String[]{"evasion"}, "component", true, null);
		itemList[33] = new BuildItemVO(33, "Cheese", "item_cheese", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{40.0}, null, 1000, null, "epic", false, null);
		itemList[34] = new BuildItemVO(34, "Magic Stick", "item_magic_stick", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{13.0}, null, 200, new String[]{"regen_health", "regen_mana", "boost_health", "boost_mana"}, "component", true, null);
		itemList[35] = new BuildItemVO(35, "Recipe: Magic Wand", "item_recipe_magic_wand", -1, null, -1, null, null, 150, null, "", false, null);
		itemList[36] = new BuildItemVO(36, "Magic Wand", "item_magic_wand", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{13.0}, null, 509, new String[]{"regen_health", "regen_mana", "boost_health", "boost_mana", "int", "agi", "str"}, "common", false, null);
		itemList[37] = new BuildItemVO(37, "Ghost", "item_ghost", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue, null, -1, new double[]{30.0}, null, 1600, new String[]{"int", "agi", "str", "hard_to_tag"}, "component", false, null);
		itemList[38] = new BuildItemVO(38, "Clarity", "item_clarity", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{100}, 0.0, null, null, 50, new String[]{"consumable"}, "consumable", false, null);
		itemList[39] = new BuildItemVO(39, "Flask", "item_flask", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{100}, 0.0, null, null, 100, new String[]{"consumable"}, "consumable", false, null);
		itemList[40] = new BuildItemVO(40, "Dust", "item_dust", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{60.0}, new int[]{5}, 180, new String[]{"consumable"}, "consumable", false, null);
		itemList[41] = new BuildItemVO(41, "Bottle", "item_bottle", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{0.5}, null, 600, new String[]{"consumable"}, "consumable", false, null);
		itemList[42] = new BuildItemVO(42, "Observer Wards", "item_ward_observer", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{500}, 0.0, new double[]{1.0}, null, 150, new String[]{"consumable"}, "consumable", false, null);
		itemList[43] = new BuildItemVO(43, "Sentry Ward", "item_ward_sentry", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{500}, 0.0, new double[]{1.0}, null, 200, new String[]{"consumable"}, "consumable", false, null);
		itemList[44] = new BuildItemVO(44, "Tango", "item_tango", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{165}, 0.0, null, null, 90, new String[]{"consumable"}, "consumable", false, null);
		itemList[45] = new BuildItemVO(45, "Courier", "item_courier", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, null, null, 150, new String[]{"consumable"}, "consumable", false, null);
		itemList[46] = new BuildItemVO(46, "Teleport Scroll", "item_tpscroll", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_CHANNELLED.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NOASSIST.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{0}, 0.0, new double[]{65.0}, new int[]{75}, 135, new String[]{"consumable", "tutorial"}, "consumable", true, null);
		itemList[47] = new BuildItemVO(47, "Recipe: Travel Boots", "item_recipe_travel_boots", -1, null, -1, null, null, 2000, null, "", false, null);
		itemList[48] = new BuildItemVO(48, "Travel Boots", "item_travel_boots", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_CHANNELLED.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, null, -1, new double[]{60.0}, new int[]{75}, 2450, new String[]{"teleport", "move_speed"}, "common", false, null);
		itemList[49] = new BuildItemVO(49, "Recipe: Phase Boots", "item_recipe_phase_boots", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[50] = new BuildItemVO(50, "Phase Boots", "item_phase_boots", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{8.0}, null, 1350, new String[]{"damage", "move_speed", "hard_to_tag"}, "common", false, null);
		itemList[51] = new BuildItemVO(51, "Demon Edge", "item_demon_edge", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2400, new String[]{"damage"}, "secret_shop", false, null);
		itemList[52] = new BuildItemVO(52, "Eagle Horn", "item_eagle", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 3300, new String[]{"agi"}, "secret_shop", false, null);
		itemList[53] = new BuildItemVO(53, "Reaver", "item_reaver", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 3200, new String[]{"str"}, "secret_shop", false, null);
		itemList[54] = new BuildItemVO(54, "Sacred Relic", "item_relic", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 3800, new String[]{"damage"}, "secret_shop", false, null);
		itemList[55] = new BuildItemVO(55, "Hyperstone", "item_hyperstone", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2100, new String[]{"attack_speed"}, "secret_shop", false, null);
		itemList[56] = new BuildItemVO(56, "Ring of Health", "item_ring_of_health", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 875, new String[]{"regen_health"}, "secret_shop", true, null);
		itemList[57] = new BuildItemVO(57, "Void Stone", "item_void_stone", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 875, new String[]{"regen_mana"}, "secret_shop", false, null);
		itemList[58] = new BuildItemVO(58, "Mystic Staff", "item_mystic_staff", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2700, new String[]{"int"}, "secret_shop", false, null);
		itemList[59] = new BuildItemVO(59, "Energy Booster", "item_energy_booster", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1000, new String[]{"mana_pool"}, "secret_shop", true, null);
		itemList[60] = new BuildItemVO(60, "Point Booster", "item_point_booster", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1200, new String[]{"mana_pool", "health_pool"}, "secret_shop", false, null);
		itemList[61] = new BuildItemVO(61, "Vitality Booster", "item_vitality_booster", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1100, new String[]{"health_pool"}, "secret_shop", false, null);
		itemList[62] = new BuildItemVO(62, "Recipe: Power Treads", "item_recipe_power_treads", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[63] = new BuildItemVO(63, "Power Treads", "item_power_treads", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, null, null, 1400, new String[]{"attack_speed", "move_speed", "int", "agi", "str"}, "common", false, null);
		itemList[64] = new BuildItemVO(64, "Recipe: Hand of Midas", "item_recipe_hand_of_midas", -1, null, -1, null, null, 1400, null, "", false, null);
		itemList[65] = new BuildItemVO(65, "Hand of Midas", "item_hand_of_midas", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{600}, 0.0, new double[]{100.0}, new int[]{0}, 1900, new String[]{"attack_speed", "hard_to_tag"}, "common", false, null);
		itemList[66] = new BuildItemVO(66, "Recipe: Oblivion Staff", "item_recipe_oblivion_staff", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[67] = new BuildItemVO(67, "Oblivion Staff", "item_oblivion_staff", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1675, new String[]{"damage", "int", "attack_speed", "regen_mana"}, "common", false, null);
		itemList[68] = new BuildItemVO(68, "Recipe: Perseverence", "item_recipe_pers", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[69] = new BuildItemVO(69, "Perseverence", "item_pers", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1750, new String[]{"damage", "regen_health", "regen_mana"}, "common", false, null);
		itemList[70] = new BuildItemVO(70, "Recipe: Poor Man's Shield", "item_recipe_poor_mans_shield", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[71] = new BuildItemVO(71, "Poor Man's Shield", "item_poor_mans_shield", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 550, new String[]{"agi", "block"}, "common", false, null);
		itemList[72] = new BuildItemVO(72, "Recipe: Bracer", "item_recipe_bracer", -1, null, -1, null, null, 190, null, "", false, null);
		itemList[73] = new BuildItemVO(73, "Bracer", "item_bracer", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 525, new String[]{"damage", "int", "agi", "str"}, "common", false, null);
		itemList[74] = new BuildItemVO(74, "Recipe: Wraith Band", "item_recipe_wraith_band", -1, null, -1, null, null, 150, null, "", false, null);
		itemList[75] = new BuildItemVO(75, "Wraith Band", "item_wraith_band", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 485, new String[]{"damage", "int", "agi", "str"}, "common", false, null);
		itemList[76] = new BuildItemVO(76, "Recipe: Null Talisman", "item_recipe_null_talisman", -1, null, -1, null, null, 135, null, "", false, null);
		itemList[77] = new BuildItemVO(77, "Null Talisman", "item_null_talisman", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 470, new String[]{"damage", "int", "agi", "str"}, "common", false, null);
		itemList[78] = new BuildItemVO(78, "Recipe: Mekasmm", "item_recipe_mekansm", -1, null, -1, null, null, 900, null, "", false, null);
		itemList[79] = new BuildItemVO(79, "Mekansm", "item_mekansm", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{45.0}, new int[]{150}, 2306, new String[]{"agi", "int", "str", "armor", "boost_health"}, "rare", false, null);
		itemList[80] = new BuildItemVO(80, "Recipe: Vladimir", "item_recipe_vladmir", -1, null, -1, null, null, 300, null, "", false, null);
		itemList[81] = new BuildItemVO(81, "Vladimir", "item_vladmir", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2050, new String[]{"lifesteal", "damage", "armor", "regen_mana"}, "rare", false, null);
		itemList[84] = new BuildItemVO(84, "Flying Courier", "item_flying_courier", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 220, new String[]{"consumable"}, "consumable", false, null);
		itemList[85] = new BuildItemVO(85, "Recipe: Buckler", "item_recipe_buckler", -1, null, -1, null, null, 200, null, "", false, null);
		itemList[86] = new BuildItemVO(86, "Buckler", "item_buckler", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{25.0}, new int[]{10}, 803, new String[]{"armor", "boost_armor"}, "rare", false, null);
		itemList[87] = new BuildItemVO(87, "Recipe: Ring of Basilius", "item_recipe_ring_of_basilius", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[88] = new BuildItemVO(88, "Ring of Basilius", "item_ring_of_basilius", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_TOGGLE.behaviourValue, null, -1, null, null, 500, new String[]{"damage", "regen_mana", "armor"}, "rare", false, null);
		itemList[89] = new BuildItemVO(89, "Recipe: Pipe", "item_recipe_pipe", -1, null, -1, null, null, 900, null, "", false, null);
		itemList[90] = new BuildItemVO(90, "Pipe", "item_pipe", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{60.0}, new int[]{100}, 3628, new String[]{"regen_health", "boost_magic_resist"}, "rare", false, null);
		itemList[91] = new BuildItemVO(91, "Recipe: Urn of Shadows", "item_recipe_urn_of_shadows", -1, null, -1, null, null, 250, null, "", false, null);
		itemList[92] = new BuildItemVO(92, "Urn of Shadows", "item_urn_of_shadows", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{950}, 0.0, new double[]{10.0}, null, 875, new String[]{"regen_mana", "str", "boost_health"}, "rare", false, null);
		itemList[93] = new BuildItemVO(93, "Recipe: Headdress", "item_recipe_headdress", -1, null, -1, null, null, 200, null, "", false, null);
		itemList[94] = new BuildItemVO(94, "Headdress", "item_headdress", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 603, new String[]{"str", "int", "agi", "regen_health"}, "rare", false, null);
		itemList[95] = new BuildItemVO(95, "Recipe: Sheepstick", "item_recipe_sheepstick", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[96] = new BuildItemVO(96, "Sheepstick", "item_sheepstick", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{800}, 0.0, new double[]{35.0}, new int[]{100}, 5675, new String[]{"int", "regen_mana", "agi", "hard_to_tag"}, "rare", false, null);
		itemList[97] = new BuildItemVO(97, "Recipe: Orchid", "item_recipe_orchid", -1, null, -1, null, null, 775, null, "", false, null);
		itemList[98] = new BuildItemVO(98, "Orchid", "item_orchid", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{900}, 0.0, new double[]{18.0}, new int[]{100}, 5025, new String[]{"int", "attack_speed", "damage", "regen_mana", "damage", "hard_to_tag"}, "rare", false, null);
		itemList[99] = new BuildItemVO(99, "Recipe: Cyclone", "item_recipe_cyclone", -1, null, -1, null, null, 500, null, "", false, null);
		itemList[100] = new BuildItemVO(100, "Cyclone", "item_cyclone", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{700}, 0.0, new double[]{30.0}, new int[]{75}, 2800, new String[]{"int", "regen_mana", "move_speed", "hard_to_tag"}, "rare", false, null);
		itemList[101] = new BuildItemVO(101, "Recipe: Force Staff", "item_recipe_force_staff", -1, null, -1, null, null, 900, null, "", false, null);
		itemList[102] = new BuildItemVO(102, "Force Staff", "item_force_staff", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{800}, 0.0, new double[]{20.0}, new int[]{25}, 2250, new String[]{"int", "damage", "attack_speed", "hard_to_tag"}, "rare", false, null);
		itemList[103] = new BuildItemVO(103, "Recipe: Dagon", "item_recipe_dagon", -1, null, -1, null, null, 1250, null, "", false, null);
		itemList[104] = new BuildItemVO(104, "Dagon", "item_dagon", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600, 650, 700, 750, 800}, 0.0, new double[]{35.0, 30.0, 25.0, 20.0, 15.0}, new int[]{180, 160, 140, 120, 100}, 2800, new String[]{"damage", "int", "str", "agi", "hard_to_tag"}, "rare", false, null);
		itemList[105] = new BuildItemVO(105, "Recipe: Necronomicon", "item_recipe_necronomicon", -1, null, -1, null, null, 1250, null, "", false, null);
		itemList[106] = new BuildItemVO(106, "Necronomicon", "item_necronomicon", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, 0.0, new double[]{80.0}, new int[]{50}, 2700, new String[]{"int", "str", "hard_to_tag", "see_invis"}, "rare", false, null);
		itemList[107] = new BuildItemVO(107, "Recipe: Scepter", "item_recipe_ultimate_scepter", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[108] = new BuildItemVO(108, "Scepter", "item_ultimate_scepter", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 4200, new String[]{"int", "str", "agi", "mana_pool", "health_pool", "hard_to_tag"}, "rare", false, null);
		itemList[109] = new BuildItemVO(109, "Recipe: Refresher", "item_recipe_refresher", -1, null, -1, null, null, 1875, null, "", false, null);
		itemList[110] = new BuildItemVO(110, "Refresher", "item_refresher", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, 0.0, new double[]{160.0}, new int[]{375}, 5300, new String[]{"regen_health", "regen_mana", "damage", "hard_to_tag"}, "rare", false, null);
		itemList[111] = new BuildItemVO(111, "Recipe: Assault Cuirass", "item_recipe_assault", -1, null, -1, null, null, 1300, null, "", false, null);
		itemList[112] = new BuildItemVO(112, "Assault Cuirass", "item_assault", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5350, new String[]{"attack_speed", "armor", "hard_to_tag"}, "epic", false, null);
		itemList[113] = new BuildItemVO(113, "Recipe: Heart", "item_recipe_heart", -1, null, -1, null, null, 1200, null, "", false, null);
		itemList[114] = new BuildItemVO(114, "Heart", "item_heart", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, new double[]{6.0}, null, 5500, new String[]{"str", "regen_health", "health_pool"}, "epic", false, null);
		itemList[115] = new BuildItemVO(115, "Recipe: Black King Bar", "item_recipe_black_king_bar", -1, null, -1, null, null, 1300, null, "", false, null);
		itemList[116] = new BuildItemVO(116, "Black King Bar", "item_black_king_bar", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{80, 75, 70, 65, 60, 55, 50}, null, 3900, new String[]{"str", "damage", "hard_to_tag"}, "epic", false, null);
		itemList[117] = new BuildItemVO(117, "Aegis of Immortality", "item_aegis", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 0, null, "artifact", false, null);
		itemList[118] = new BuildItemVO(118, "Recipe: Shiva's  Guard", "item_recipe_shivas_guard", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[119] = new BuildItemVO(119, "Shiva's", "item_shivas_guard", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{30}, new int[]{100}, 4700, new String[]{"int", "armor", "hard_to_tag"}, "epic", false, null);
		itemList[120] = new BuildItemVO(120, "Recipe: Bloodstone", "item_recipe_bloodstone", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[121] = new BuildItemVO(121, "Bloodstone", "item_bloodstone", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{150}, 0.0, new double[]{300.0}, null, 5050, new String[]{"regen_health", "regen_mana", "mana_pool", "health_pool"}, "epic", false, null);
		itemList[122] = new BuildItemVO(122, "Recipe: Sphere", "item_recipe_sphere", -1, null, -1, null, null, 1325, null, "", false, null);
		itemList[123] = new BuildItemVO(123, "Sphere", "item_sphere", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5175, new String[]{"regen_health", "regen_mana", "str", "agi", "int", "hard_to_tag"}, "epic", false, null);
		itemList[124] = new BuildItemVO(124, "Recipe: Vanguard", "item_recipe_vanguard", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[125] = new BuildItemVO(125, "Vanguard", "item_vanguard", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2225, new String[]{"regen_health", "block", "health_pool"}, "epic", false, null);
		itemList[126] = new BuildItemVO(126, "Recipe: Blade Mail", "item_recipe_blade_mail", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[127] = new BuildItemVO(127, "Blade Mail", "item_blade_mail", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{17.0}, new int[]{25}, 2200, new String[]{"damage", "armor", "int", "hard_to_tag"}, "epic", false, null);
		itemList[128] = new BuildItemVO(128, "Recipe: Soul Booster", "item_recipe_soul_booster", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[129] = new BuildItemVO(129, "Soul Booster", "item_soul_booster", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 3300, new String[]{"regen_health", "regen_mana", "health_pool", "mana_pool"}, "epic", false, null);
		itemList[130] = new BuildItemVO(130, "Recipe: Hood of Defiance", "item_recipe_hood_of_defiance", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[131] = new BuildItemVO(131, "Hood of Defiance", "item_hood_of_defiance", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2125, new String[]{"regen_health", "magic_resist"}, "epic", false, null);
		itemList[132] = new BuildItemVO(132, "Recipe: Rapier", "item_recipe_rapier", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[133] = new BuildItemVO(133, "Rapier", "item_rapier", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 6200, new String[]{"damage"}, "epic", false, null);
		itemList[134] = new BuildItemVO(134, "Recipe: Monkey King Bar", "item_recipe_monkey_king_bar", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[135] = new BuildItemVO(135, "Monkey King Bar", "item_monkey_king_bar", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5400, new String[]{"damage", "attack_speed", "hard_to_tag"}, "epic", false, null);
		itemList[136] = new BuildItemVO(136, "Recipe: Radiance", "item_recipe_radiance", -1, null, -1, null, null, 1350, null, "", false, null);
		itemList[137] = new BuildItemVO(137, "Radiance", "item_radiance", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_TOGGLE.behaviourValue, null, -1, null, null, 5150, new String[]{"damage"}, "epic", false, null);
		itemList[138] = new BuildItemVO(138, "Recipe: Butterfly", "item_recipe_butterfly", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[139] = new BuildItemVO(139, "Butterfly", "item_butterfly", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 6000, new String[]{"agi", "damage", "evasion", "attack_speed"}, "epic", false, null);
		itemList[140] = new BuildItemVO(140, "Recipe: Greater Crit", "item_recipe_greater_crit", -1, null, -1, null, null, 1000, null, "", false, null);
		itemList[141] = new BuildItemVO(141, "Greater Crit", "item_greater_crit", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5550, new String[]{"damage", "crit"}, "epic", false, null);
		itemList[142] = new BuildItemVO(142, "Recipe: Basher", "item_recipe_basher", -1, null, -1, null, null, 1000, null, "", false, new String[]{"npc_dota_hero_spirit_breaker", "npc_dota_hero_faceless_void", "npc_dota_hero_slardar", "npc_dota_hero_troll_warlord"});
		itemList[143] = new BuildItemVO(143, "Basher", "item_basher", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, new double[]{2.0}, null, 2950, new String[]{"damage", "str", "hard_to_tag"}, "epic", false, null);
		itemList[144] = new BuildItemVO(144, "Recipe: Battlefury", "item_recipe_bfury", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[145] = new BuildItemVO(145, "Battlefury", "item_bfury", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 4350, new String[]{"damage", "health_regen", "mana_regen", "hard_to_tag"}, "epic", false, null);
		itemList[146] = new BuildItemVO(146, "Recipe: Manta", "item_recipe_manta", -1, null, -1, null, null, 900, null, "", false, null);
		itemList[147] = new BuildItemVO(147, "Manta", "item_manta", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, null, 0.0, new double[]{50.0}, new int[]{165}, 5050, new String[]{"agi", "str", "int", "attack_speed", "move_speed", "hard_to_tag"}, "epic", false, null);
		itemList[148] = new BuildItemVO(148, "Recipe: Lesser Crit", "item_recipe_lesser_crit", -1, null, -1, null, null, 500, null, "", false, null);
		itemList[149] = new BuildItemVO(149, "Lesser Crit", "item_lesser_crit", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2150, new String[]{"damage", "crit"}, "epic", false, null);
		itemList[150] = new BuildItemVO(150, "Recipe: Armlet", "item_recipe_armlet", -1, null, -1, null, null, 700, null, "", false, null);
		itemList[151] = new BuildItemVO(151, "Armlet", "item_armlet", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_TOGGLE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{2.0}, null, 2600, new String[]{"damage", "attack_speed", "armor", "regen_health", "hard_to_tag"}, "epic", false, null);
		itemList[183] = new BuildItemVO(183, "Recipe: Invisibility Sword", "item_recipe_invis_sword", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[152] = new BuildItemVO(152, "Invisibility Sword", "item_invis_sword", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{18.0}, new int[]{75}, 3000, new String[]{"damage", "attack_speed", "movespeed", "hard_to_tag"}, "epic", false, null);
		itemList[153] = new BuildItemVO(153, "Recipe: Sange and Yasha", "item_recipe_sange_and_yasha", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[154] = new BuildItemVO(154, "Sange and Yasha", "item_sange_and_yasha", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 4100, new String[]{"damage", "str", "agi", "attack_speed", "unique"}, "artifact", false, null);
		itemList[155] = new BuildItemVO(155, "Recipe: Satanic", "item_recipe_satanic", -1, null, -1, null, null, 1100, null, "", false, null);
		itemList[156] = new BuildItemVO(156, "Satanic", "item_satanic", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{35.0}, null, 6150, new String[]{"damage", "str", "armor", "unique", "hard_to_tag"}, "artifact", false, null);
		itemList[157] = new BuildItemVO(157, "Recipe: Mjollnir", "item_recipe_mjollnir", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[158] = new BuildItemVO(158, "Mjollnir", "item_mjollnir", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600}, 0.0, new double[]{35.0}, new int[]{50}, 5400, new String[]{"damage", "attack_speed", "unique"}, "artifact", false, null);
		itemList[159] = new BuildItemVO(159, "Recipe: Skadi", "item_recipe_skadi", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[160] = new BuildItemVO(160, "Skadi", "item_skadi", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5675, new String[]{"agi", "str", "int", "hard_to_tag", "mana_pool", "health_pool", "unique"}, "artifact", false, null);
		itemList[161] = new BuildItemVO(161, "Recipe: Sange", "item_recipe_sange", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[162] = new BuildItemVO(162, "Sange", "item_sange", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2050, new String[]{"damage", "str", "unique"}, "artifact", false, null);
		itemList[163] = new BuildItemVO(163, "Recipe: Helm of the Dominator", "item_recipe_helm_of_the_dominator", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[164] = new BuildItemVO(164, "Helm of the Dominator", "item_helm_of_the_dominator", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{700}, 0.0, new double[]{60.0}, new int[]{75}, 1850, new String[]{"damage", "armor", "unique", "hard_to_tag"}, "artifact", false, null);
		itemList[165] = new BuildItemVO(165, "Recipe: Maelstrom", "item_recipe_maelstrom", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[166] = new BuildItemVO(166, "Maelstrom", "item_maelstrom", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2700, new String[]{"damage", "attack_speed", "unique"}, "artifact", false, null);
		itemList[167] = new BuildItemVO(167, "Recipe: Desolator", "item_recipe_desolator", -1, null, -1, null, null, 900, null, "", false, null);
		itemList[168] = new BuildItemVO(168, "Desolator", "item_desolator", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 4100, new String[]{"damage", "unique"}, "artifact", false, null);
		itemList[169] = new BuildItemVO(169, "Recipe: Yasha", "item_recipe_yasha", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[170] = new BuildItemVO(170, "Yasha", "item_yasha", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2050, new String[]{"agi", "attack_speed", "move_speed"}, "artifact", false, null);
		itemList[171] = new BuildItemVO(171, "Recipe: Mask of Madness", "item_recipe_mask_of_madness", -1, null, -1, null, null, 1000, null, "", false, null);
		itemList[172] = new BuildItemVO(172, "Mask of Madness", "item_mask_of_madness", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{25.0}, new int[]{25}, 1900, new String[]{"unique", "hard_to_tag"}, "artifact", false, null);
		itemList[173] = new BuildItemVO(173, "Recipe: Diffusal Blade", "item_recipe_diffusal_blade", -1, null, -1, null, null, 850, null, "", false, null);
		itemList[174] = new BuildItemVO(174, "Diffusal Blade", "item_diffusal_blade", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600}, 0.0, new double[]{8.0}, new int[]{0}, 3300, new String[]{"agi", "int", "unique", "hard_to_tag"}, "artifact", false, null);
		itemList[175] = new BuildItemVO(175, "Recipe: Ethereal Blade", "item_recipe_ethereal_blade", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{800}, 0.0, new double[]{30.0}, new int[]{150}, 0, null, "epic", false, null);
		itemList[177] = new BuildItemVO(177, "Recipe: Soul Ring", "item_recipe_soul_ring", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue, null, -1, new double[]{30.0}, new int[]{0}, 125, null, "common", false, null);
		itemList[179] = new BuildItemVO(179, "Recipe: Arcane Boots", "item_recipe_arcane_boots", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[180] = new BuildItemVO(180, "Arcane Boots", "item_arcane_boots", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{55.0}, new int[]{25}, 1450, new String[]{"move_speed", "boost_mana", "mana_pool"}, "rare", false, null);
		itemList[181] = new BuildItemVO(181, "Orb of Venom", "item_orb_of_venom", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 275, new String[]{"hard_to_tag"}, "secret_shop", true, null);
		itemList[184] = new BuildItemVO(184, "Recipe: Ancient Janggo of Endurance", "item_recipe_ancient_janggo", -1, null, -1, null, null, 800, null, "", false, null);
		itemList[185] = new BuildItemVO(185, "Ancient Janggo of Endurance", "item_ancient_janggo", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{30.0}, null, 1775, new String[]{"str", "agi", "int", "damage", "move_speed", "attack_speed", "hard_to_tag"}, "rare", false, null);
		itemList[186] = new BuildItemVO(186, "Recipe: Medallion of Courage", "item_recipe_medallion_of_courage", -1, null, -1, null, null, 200, null, "", false, null);
		itemList[187] = new BuildItemVO(187, "Medallion of Courage", "item_medallion_of_courage", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{1000}, -1, new double[]{7.0}, null, 1075, new String[]{"armor", "regen_mana", "hard_to_tag"}, "rare", false, null);
		itemList[188] = new BuildItemVO(188, "Smoke of Deceit", "item_smoke_of_deceit", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, null, -1, new double[]{90.0}, null, 100, new String[]{"consumable"}, "consumable", false, null);
		itemList[189] = new BuildItemVO(189, "Recipe: Veil of Discord", "item_recipe_veil_of_discord", -1, null, -1, null, null, 1250, null, "", false, null);
		itemList[190] = new BuildItemVO(190, "Veil of discord", "item_veil_of_discord", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_AOE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{1000}, 0.0, new double[]{30}, new int[]{75}, 2650, new String[]{"int", "armor", "regen_health", "hard_to_tag"}, "rare", false, null);
		itemList[205] = new BuildItemVO(205, "Recipe: Rod of Atos", "item_recipe_rod_of_atos", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[206] = new BuildItemVO(206, "Rod of Atos", "item_rod_of_atos", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{1200}, 0.0, new double[]{16}, new int[]{50}, 3100, new String[]{"int", "armor", "regen_health"}, "rare", false, null);
		itemList[207] = new BuildItemVO(207, "Recipe: Abyssal Blade", "item_recipe_abyssal_blade", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[208] = new BuildItemVO(208, "Abyssal Blade", "item_abyssal_blade", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{140}, 0.0, new double[]{60}, new int[]{150}, 6750, new String[]{"damage", "str", "hard_to_tag"}, "epic", false, null);
		itemList[209] = new BuildItemVO(209, "Recipe: Heaven's Halberd", "item_recipe_heavens_halberd", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[210] = new BuildItemVO(210, "Heaven's Halberd", "item_heavens_halberd", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600}, 0.0, new double[]{30}, new int[]{100}, 3850, new String[]{"str", "damage", "evasion"}, "artifact", false, null);
		itemList[211] = new BuildItemVO(211, "Recipe: Ring of Aquila", "item_recipe_ring_of_aquila", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[212] = new BuildItemVO(212, "Ring of Aquila", "item_ring_of_aquila", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_TOGGLE.behaviourValue, null, -1, null, null, 985, null, "rare", false, null);
		itemList[213] = new BuildItemVO(213, "Recipe: Tranquil Boots", "item_recipe_tranquil_boots", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[214] = new BuildItemVO(214, "Tranquil Boots", "item_tranquil_boots", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{60.0}, new int[]{25}, 975, new String[]{"move_speed", "regen_health", "armor"}, "rare", false, null);
		itemList[215] = new BuildItemVO(215, "Shadow Amulet", "item_shadow_amulet", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_MOVEMENT.behaviourValue, null, -1, new double[]{0.0}, new int[]{0}, 1600, null, "", false, null);
		itemList[216] = new BuildItemVO(216, "Halloween Candy Corn", "item_halloween_candy_corn", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{350}, 0.0, new double[]{0.0}, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[217] = new BuildItemVO(217, "Mystery Rune Meat Hook ", "item_mystery_hook", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{1300}, 0.3, new double[]{11.0}, new int[]{140}, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[218] = new BuildItemVO(218, "Mystery Rune Mirana Arrow", "item_mystery_arrow", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DIRECTIONAL.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{3000}, 0.5, new double[]{2.0}, new int[]{0}, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[219] = new BuildItemVO(219, "Mystery Missile", "item_mystery_missile", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{1050}, 0.3, new double[]{20.0}, new int[]{0}, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[220] = new BuildItemVO(220, "Mystery Toss", "item_mystery_toss", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_AOE.behaviourValue, new int[]{1300}, 0.0, new double[]{2.0}, new int[]{0}, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[221] = new BuildItemVO(221, "Mystery Vacuum", "item_mystery_vacuum", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_AOE.behaviourValue, new int[]{500}, 0.4, new double[]{2.0}, new int[]{0}, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[226] = new BuildItemVO(226, "Halloween Rapier", "item_halloween_rapier", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 6200, new String[]{"damage"}, "epic", false, null);
		itemList[228] = new BuildItemVO(228, "Unknown", "item_greevil_whistle", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_CHANNELLED.behaviourValue, new int[]{0}, 0.0, new double[]{120.0}, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[235] = new BuildItemVO(235, "Toggleable whistle", "item_greevil_whistle_toggle", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_CHANNELLED.behaviourValue, new int[]{0}, 0.0, new double[]{2.0}, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[227] = new BuildItemVO(227, "XMas present", "item_present", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, new int[]{350}, 0.0, new double[]{0.0}, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[229] = new BuildItemVO(229, "Xmas Stocking", "item_winter_stocking", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, new int[]{350}, 0.0, new double[]{0.0}, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[230] = new BuildItemVO(230, "XMas Skates", "item_winter_skates", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 0, new String[]{"move_speed"}, "component", false, null);
		itemList[231] = new BuildItemVO(231, "Winter Cake", "item_winter_cake", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{150}, 0.0, null, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[232] = new BuildItemVO(232, "Winter Cookie", "item_winter_cookie", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{150}, 0.0, null, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[233] = new BuildItemVO(233, "Winter Coco", "item_winter_coco", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{150}, 0.0, null, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[234] = new BuildItemVO(234, "Winter Ham", "item_winter_ham", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{150}, 0.0, null, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[236] = new BuildItemVO(236, "Winter Kringle", "item_winter_kringle", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK.behaviourValue, new int[]{150}, 0.0, null, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[237] = new BuildItemVO(237, "Greevil Mushroom", "item_winter_mushroom", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, new int[]{150}, 0.0, null, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[238] = new BuildItemVO(238, "Greevil Treat", "item_winter_greevil_treat", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, new int[]{150}, 0.0, null, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[239] = new BuildItemVO(239, "Greevil Chow", "item_winter_greevil_garbage", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, new int[]{150}, 0.0, null, null, 0, new String[]{"consumable"}, "consumable", false, null);
		itemList[240] = new BuildItemVO(240, "Greevil Blink dagger", "item_winter_greevil_chewy", AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES.behaviourValue + AbilityVO.Behavior.DOTA_ABILITY_BEHAVIOR_CHANNELLED.behaviourValue, new int[]{400}, 0.0, new double[]{10.0}, new int[]{0}, 0, new String[]{"consumable"}, "consumable", false, null);

	}
	
	public BuildItemVO getItemById(int id) {
		BuildItemVO item = null;
		
		if(id < itemList.length) {
			item = itemList[id];
		}
		
		return item;
	}
}
