package nl.ansuz.android.steam.dota.util;

import nl.ansuz.android.steam.dota.vo.BuildItemVO;

/**
 * Auto-generated Hero build item list.
 * 
 * This class gets generated by passing the DotA game file 
 * "scripts/npc/items.txt" that can be extracted from 
 * "<path to steam>/Steam/steamapps/common/dota 2 beta/dota/pak01_dir.vpk"
 * 
 * Use tools/itemparser/BuildItemsParser.py to generate.
 * 
 * @author Wijnand
 */
public class HeroBuildItemList {

	private BuildItemVO[] itemList;
	
	/**
	 * CONSTRUCTOR
	 */
	public HeroBuildItemList() {
		init();
	}

	/**
	 * Initializes this class.
	 */
	private void init() {
		createItemList();
	}

	/**
	 * Constructs the Hero build item list.
	 */
	private void createItemList() {
		itemList = new BuildItemVO[205];
		itemList[1] = new BuildItemVO(1, "item_blink", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_DIRECTIONAL.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES.behaviourValue, new int[]{0}, 0.0, new double[]{14.0}, new int[]{75}, 2150, new String[]{"teleport"}, "component", true, new String[]{"npc_dota_hero_vengefulspirit", "npc_dota_hero_pudge"});
		itemList[2] = new BuildItemVO(2, "item_blades_of_attack", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"damage", "tutorial"}, "component", true, null);
		itemList[3] = new BuildItemVO(3, "item_broadsword", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1200, new String[]{"damage"}, "component", false, null);
		itemList[4] = new BuildItemVO(4, "item_chainmail", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 550, new String[]{"armor"}, "component", true, null);
		itemList[5] = new BuildItemVO(5, "item_claymore", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1400, new String[]{"damage"}, "component", false, null);
		itemList[6] = new BuildItemVO(6, "item_helm_of_iron_will", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 950, new String[]{"armor", "regen_health"}, "component", true, null);
		itemList[7] = new BuildItemVO(7, "item_javelin", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1500, new String[]{"damage"}, "component", false, null);
		itemList[8] = new BuildItemVO(8, "item_mithril_hammer", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1600, new String[]{"damage"}, "component", false, null);
		itemList[9] = new BuildItemVO(9, "item_platemail", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1400, new String[]{"armor"}, "component", false, null);
		itemList[10] = new BuildItemVO(10, "item_quarterstaff", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 900, new String[]{"damage", "attack_speed"}, "component", true, null);
		itemList[11] = new BuildItemVO(11, "item_quelling_blade", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{165}, 0.0, new double[]{5.0}, new int[]{0}, 225, new String[]{"damage"}, "component", true, null);
		itemList[12] = new BuildItemVO(12, "item_ring_of_protection", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 175, new String[]{"armor"}, "component", false, null);
		itemList[182] = new BuildItemVO(182, "item_stout_shield", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 250, new String[]{"block"}, "component", true, null);
		itemList[13] = new BuildItemVO(13, "item_gauntlets", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 150, new String[]{"str"}, "component", false, null);
		itemList[14] = new BuildItemVO(14, "item_slippers", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 150, new String[]{"agi"}, "component", true, null);
		itemList[15] = new BuildItemVO(15, "item_mantle", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 150, new String[]{"int"}, "component", false, null);
		itemList[16] = new BuildItemVO(16, "item_branches", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 53, new String[]{"agi", "int", "str"}, "component", false, null);
		itemList[17] = new BuildItemVO(17, "item_belt_of_strength", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"str"}, "component", true, null);
		itemList[18] = new BuildItemVO(18, "item_boots_of_elves", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"agi"}, "component", true, null);
		itemList[19] = new BuildItemVO(19, "item_robe", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"int"}, "component", true, null);
		itemList[20] = new BuildItemVO(20, "item_circlet", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 185, new String[]{"agi", "int", "str"}, "component", false, null);
		itemList[21] = new BuildItemVO(21, "item_ogre_axe", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1000, new String[]{"str"}, "component", false, null);
		itemList[22] = new BuildItemVO(22, "item_blade_of_alacrity", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1000, new String[]{"agi"}, "component", false, null);
		itemList[23] = new BuildItemVO(23, "item_staff_of_wizardry", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1000, new String[]{"int"}, "component", false, null);
		itemList[24] = new BuildItemVO(24, "item_ultimate_orb", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2100, new String[]{"agi", "int", "str"}, "component", true, null);
		itemList[25] = new BuildItemVO(25, "item_gloves", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 500, new String[]{"attack_speed"}, "component", true, null);
		itemList[26] = new BuildItemVO(26, "item_lifesteal", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 900, new String[]{"unique"}, "component", true, null);
		itemList[27] = new BuildItemVO(27, "item_ring_of_regen", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 350, new String[]{"regen_health"}, "component", true, null);
		itemList[28] = new BuildItemVO(28, "item_sobi_mask", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 325, new String[]{"regen_mana"}, "component", true, null);
		itemList[29] = new BuildItemVO(29, "item_boots", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 500, new String[]{"move_speed"}, "component", true, null);
		itemList[30] = new BuildItemVO(30, "item_gem", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 700, new String[]{"see_invis"}, "component", false, null);
		itemList[31] = new BuildItemVO(31, "item_cloak", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 550, new String[]{"magic_resist"}, "component", true, null);
		itemList[32] = new BuildItemVO(32, "item_talisman_of_evasion", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1800, new String[]{"evasion"}, "component", true, null);
		itemList[33] = new BuildItemVO(33, "item_cheese", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, null, null, 1000, null, "epic", false, null);
		itemList[34] = new BuildItemVO(34, "item_magic_stick", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{13.0}, null, 200, new String[]{"regen_health", "regen_mana", "boost_health", "boost_mana"}, "component", true, null);
		itemList[35] = new BuildItemVO(35, "item_recipe_magic_wand", -1, null, -1, null, null, 150, null, "", false, null);
		itemList[36] = new BuildItemVO(36, "item_magic_wand", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{13.0}, null, 509, new String[]{"regen_health", "regen_mana", "boost_health", "boost_mana", "int", "agi", "str"}, "common", false, null);
		itemList[37] = new BuildItemVO(37, "item_ghost", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue, null, -1, new double[]{30.0}, null, 1600, new String[]{"int", "agi", "str", "hard_to_tag"}, "component", false, null);
		itemList[38] = new BuildItemVO(38, "item_clarity", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue, new int[]{100}, 0.0, null, null, 50, new String[]{"consumable"}, "consumable", false, null);
		itemList[39] = new BuildItemVO(39, "item_flask", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue, new int[]{100}, 0.0, null, null, 100, new String[]{"consumable"}, "consumable", false, null);
		itemList[40] = new BuildItemVO(40, "item_dust", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{60.0}, new int[]{5}, 180, new String[]{"consumable"}, "consumable", false, null);
		itemList[41] = new BuildItemVO(41, "item_bottle", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{0.5}, null, 600, new String[]{"consumable"}, "consumable", false, null);
		itemList[42] = new BuildItemVO(42, "item_ward_observer", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{500}, 0.0, null, null, 200, new String[]{"consumable"}, "consumable", false, null);
		itemList[43] = new BuildItemVO(43, "item_ward_sentry", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{500}, 0.0, null, null, 200, new String[]{"consumable"}, "consumable", false, null);
		itemList[44] = new BuildItemVO(44, "item_tango", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{165}, 0.0, null, null, 90, new String[]{"consumable"}, "consumable", false, null);
		itemList[45] = new BuildItemVO(45, "item_courier", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, null, null, 170, new String[]{"consumable"}, "consumable", false, null);
		itemList[46] = new BuildItemVO(46, "item_tpscroll", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_CHANNELLED.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NOASSIST.behaviourValue, new int[]{0}, 0.0, new double[]{65.0}, new int[]{75}, 135, new String[]{"consumable", "tutorial"}, "consumable", true, null);
		itemList[47] = new BuildItemVO(47, "item_recipe_travel_boots", -1, null, -1, null, null, 2200, null, "", false, null);
		itemList[48] = new BuildItemVO(48, "item_travel_boots", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_CHANNELLED.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{60.0}, new int[]{75}, 2700, new String[]{"teleport", "move_speed"}, "common", false, null);
		itemList[49] = new BuildItemVO(49, "item_recipe_phase_boots", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[50] = new BuildItemVO(50, "item_phase_boots", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{8.0}, null, 1400, new String[]{"damage", "move_speed", "hard_to_tag"}, "common", false, null);
		itemList[51] = new BuildItemVO(51, "item_demon_edge", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2400, new String[]{"damage"}, "secret_shop", false, null);
		itemList[52] = new BuildItemVO(52, "item_eagle", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 3300, new String[]{"agi"}, "secret_shop", false, null);
		itemList[53] = new BuildItemVO(53, "item_reaver", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 3200, new String[]{"str"}, "secret_shop", false, null);
		itemList[54] = new BuildItemVO(54, "item_relic", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 3800, new String[]{"damage"}, "secret_shop", false, null);
		itemList[55] = new BuildItemVO(55, "item_hyperstone", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2100, new String[]{"attack_speed"}, "secret_shop", false, null);
		itemList[56] = new BuildItemVO(56, "item_ring_of_health", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 875, new String[]{"regen_health"}, "secret_shop", true, null);
		itemList[57] = new BuildItemVO(57, "item_void_stone", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 875, new String[]{"regen_mana"}, "secret_shop", false, null);
		itemList[58] = new BuildItemVO(58, "item_mystic_staff", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2700, new String[]{"int"}, "secret_shop", false, null);
		itemList[59] = new BuildItemVO(59, "item_energy_booster", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1000, new String[]{"mana_pool"}, "secret_shop", true, null);
		itemList[60] = new BuildItemVO(60, "item_point_booster", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1200, new String[]{"mana_pool", "health_pool"}, "secret_shop", false, null);
		itemList[61] = new BuildItemVO(61, "item_vitality_booster", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1100, new String[]{"health_pool"}, "secret_shop", false, null);
		itemList[62] = new BuildItemVO(62, "item_recipe_power_treads", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[63] = new BuildItemVO(63, "item_power_treads", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, null, null, 1450, new String[]{"attack_speed", "move_speed", "int", "agi", "str"}, "common", false, null);
		itemList[64] = new BuildItemVO(64, "item_recipe_hand_of_midas", -1, null, -1, null, null, 1400, null, "", false, null);
		itemList[65] = new BuildItemVO(65, "item_hand_of_midas", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600}, 0.0, new double[]{100.0}, new int[]{0}, 1900, new String[]{"attack_speed", "hard_to_tag"}, "common", false, null);
		itemList[66] = new BuildItemVO(66, "item_recipe_oblivion_staff", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[67] = new BuildItemVO(67, "item_oblivion_staff", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1675, new String[]{"damage", "int", "attack_speed", "regen_mana"}, "common", false, null);
		itemList[68] = new BuildItemVO(68, "item_recipe_pers", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[69] = new BuildItemVO(69, "item_pers", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 1750, new String[]{"damage", "regen_health", "regen_mana"}, "common", false, null);
		itemList[70] = new BuildItemVO(70, "item_recipe_poor_mans_shield", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[71] = new BuildItemVO(71, "item_poor_mans_shield", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 550, new String[]{"agi", "block"}, "common", false, null);
		itemList[72] = new BuildItemVO(72, "item_recipe_bracer", -1, null, -1, null, null, 190, null, "", false, null);
		itemList[73] = new BuildItemVO(73, "item_bracer", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 525, new String[]{"damage", "int", "agi", "str"}, "common", false, null);
		itemList[74] = new BuildItemVO(74, "item_recipe_wraith_band", -1, null, -1, null, null, 150, null, "", false, null);
		itemList[75] = new BuildItemVO(75, "item_wraith_band", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 485, new String[]{"damage", "int", "agi", "str"}, "common", false, null);
		itemList[76] = new BuildItemVO(76, "item_recipe_null_talisman", -1, null, -1, null, null, 170, null, "", false, null);
		itemList[77] = new BuildItemVO(77, "item_null_talisman", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 505, new String[]{"damage", "int", "agi", "str"}, "common", false, null);
		itemList[78] = new BuildItemVO(78, "item_recipe_mekansm", -1, null, -1, null, null, 900, null, "", false, null);
		itemList[79] = new BuildItemVO(79, "item_mekansm", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{45.0}, new int[]{150}, 2306, new String[]{"agi", "int", "str", "armor", "boost_health"}, "rare", false, null);
		itemList[80] = new BuildItemVO(80, "item_recipe_vladmir", -1, null, -1, null, null, 300, null, "", false, null);
		itemList[81] = new BuildItemVO(81, "item_vladmir", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2050, new String[]{"lifesteal", "damage", "armor", "regen_mana"}, "rare", false, null);
		itemList[84] = new BuildItemVO(84, "item_flying_courier", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 200, new String[]{"consumable"}, "rare", false, null);
		itemList[85] = new BuildItemVO(85, "item_recipe_buckler", -1, null, -1, null, null, 200, null, "", false, null);
		itemList[86] = new BuildItemVO(86, "item_buckler", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{25.0}, new int[]{10}, 803, new String[]{"armor", "boost_armor"}, "rare", false, null);
		itemList[87] = new BuildItemVO(87, "item_recipe_ring_of_basilius", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[88] = new BuildItemVO(88, "item_ring_of_basilius", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_TOGGLE.behaviourValue, null, -1, null, null, 500, new String[]{"damage", "regen_mana", "armor"}, "rare", false, null);
		itemList[89] = new BuildItemVO(89, "item_recipe_pipe", -1, null, -1, null, null, 900, null, "", false, null);
		itemList[90] = new BuildItemVO(90, "item_pipe", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{60.0}, new int[]{100}, 3628, new String[]{"regen_health", "boost_magic_resist"}, "rare", false, null);
		itemList[91] = new BuildItemVO(91, "item_recipe_urn_of_shadows", -1, null, -1, null, null, 250, null, "", false, null);
		itemList[92] = new BuildItemVO(92, "item_urn_of_shadows", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{950}, 0.0, new double[]{10.0}, null, 875, new String[]{"regen_mana", "str", "boost_health"}, "rare", false, null);
		itemList[93] = new BuildItemVO(93, "item_recipe_headdress", -1, null, -1, null, null, 200, null, "", false, null);
		itemList[94] = new BuildItemVO(94, "item_headdress", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 603, new String[]{"str", "int", "agi", "regen_health"}, "rare", false, null);
		itemList[95] = new BuildItemVO(95, "item_recipe_sheepstick", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[96] = new BuildItemVO(96, "item_sheepstick", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{800}, 0.0, new double[]{35.0}, new int[]{100}, 5675, new String[]{"int", "regen_mana", "agi", "hard_to_tag"}, "rare", false, null);
		itemList[97] = new BuildItemVO(97, "item_recipe_orchid", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[98] = new BuildItemVO(98, "item_orchid", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{900}, 0.0, new double[]{18.0}, new int[]{100}, 5025, new String[]{"int", "attack_speed", "damage", "regen_mana", "damage", "hard_to_tag"}, "rare", false, null);
		itemList[99] = new BuildItemVO(99, "item_recipe_cyclone", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[100] = new BuildItemVO(100, "item_cyclone", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{700}, 0.0, new double[]{30.0}, new int[]{75}, 2800, new String[]{"int", "regen_mana", "move_speed", "hard_to_tag"}, "rare", false, null);
		itemList[101] = new BuildItemVO(101, "item_recipe_force_staff", -1, null, -1, null, null, 300, null, "", false, null);
		itemList[102] = new BuildItemVO(102, "item_force_staff", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600}, 0.0, new double[]{20.0}, new int[]{25}, 2200, new String[]{"int", "damage", "attack_speed", "hard_to_tag"}, "rare", false, null);
		itemList[103] = new BuildItemVO(103, "item_recipe_dagon", -1, null, -1, null, null, 1300, null, "", false, null);
		itemList[197] = new BuildItemVO(197, "item_recipe_dagon_2", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[198] = new BuildItemVO(198, "item_recipe_dagon_3", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[199] = new BuildItemVO(199, "item_recipe_dagon_4", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[200] = new BuildItemVO(200, "item_recipe_dagon_5", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[104] = new BuildItemVO(104, "item_dagon", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600, 650, 700, 750, 800}, 0.0, new double[]{40.0, 36.0, 32.0, 28.0, 24.0}, new int[]{180, 160, 140, 120, 100}, 2850, new String[]{"damage", "int", "str", "agi", "hard_to_tag"}, "rare", false, null);
		itemList[201] = new BuildItemVO(201, "item_dagon_2", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600, 650, 700, 750, 800}, 0.0, new double[]{40.0, 36.0, 32.0, 28.0, 24.0}, new int[]{180, 160, 140, 120, 100}, 2850, new String[]{"damage", "int", "str", "agi", "hard_to_tag"}, "rare", false, null);
		itemList[202] = new BuildItemVO(202, "item_dagon_3", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600, 650, 700, 750, 800}, 0.0, new double[]{40.0, 36.0, 32.0, 28.0, 24.0}, new int[]{180, 160, 140, 120, 100}, 2850, new String[]{"damage", "int", "str", "agi", "hard_to_tag"}, "rare", false, null);
		itemList[203] = new BuildItemVO(203, "item_dagon_4", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600, 650, 700, 750, 800}, 0.0, new double[]{40.0, 36.0, 32.0, 28.0, 24.0}, new int[]{180, 160, 140, 120, 100}, 2850, new String[]{"damage", "int", "str", "agi", "hard_to_tag"}, "rare", false, null);
		itemList[204] = new BuildItemVO(204, "item_dagon_5", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600, 650, 700, 750, 800}, 0.0, new double[]{40.0, 36.0, 32.0, 28.0, 24.0}, new int[]{180, 160, 140, 120, 100}, 2850, new String[]{"damage", "int", "str", "agi", "hard_to_tag"}, "rare", false, null);
		itemList[105] = new BuildItemVO(105, "item_recipe_necronomicon", -1, null, -1, null, null, 1250, null, "", false, null);
		itemList[191] = new BuildItemVO(191, "item_recipe_necronomicon_2", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[192] = new BuildItemVO(192, "item_recipe_necronomicon_3", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[106] = new BuildItemVO(106, "item_necronomicon", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, 0.0, new double[]{80.0}, new int[]{50}, 2700, new String[]{"int", "str", "hard_to_tag", "see_invis"}, "rare", false, null);
		itemList[193] = new BuildItemVO(193, "item_necronomicon_2", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, 0.0, new double[]{80.0}, new int[]{50}, 2700, new String[]{"int", "str", "hard_to_tag", "see_invis"}, "rare", false, null);
		itemList[194] = new BuildItemVO(194, "item_necronomicon_3", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, 0.0, new double[]{80.0}, new int[]{50}, 2700, new String[]{"int", "str", "hard_to_tag", "see_invis"}, "rare", false, null);
		itemList[107] = new BuildItemVO(107, "item_recipe_ultimate_scepter", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[108] = new BuildItemVO(108, "item_ultimate_scepter", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 4200, new String[]{"int", "str", "agi", "mana_pool", "health_pool", "hard_to_tag"}, "rare", false, null);
		itemList[109] = new BuildItemVO(109, "item_recipe_refresher", -1, null, -1, null, null, 1875, null, "", false, null);
		itemList[110] = new BuildItemVO(110, "item_refresher", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, 0.0, new double[]{160.0}, new int[]{375}, 5300, new String[]{"regen_health", "regen_mana", "damage", "hard_to_tag"}, "rare", false, null);
		itemList[111] = new BuildItemVO(111, "item_recipe_assault", -1, null, -1, null, null, 1300, null, "", false, null);
		itemList[112] = new BuildItemVO(112, "item_assault", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5350, new String[]{"attack_speed", "armor", "hard_to_tag"}, "epic", false, null);
		itemList[113] = new BuildItemVO(113, "item_recipe_heart", -1, null, -1, null, null, 1200, null, "", false, null);
		itemList[114] = new BuildItemVO(114, "item_heart", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, new double[]{6.0}, null, 5500, new String[]{"str", "regen_health", "health_pool"}, "epic", false, null);
		itemList[115] = new BuildItemVO(115, "item_recipe_black_king_bar", -1, null, -1, null, null, 1300, null, "", false, null);
		itemList[116] = new BuildItemVO(116, "item_black_king_bar", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{80, 75, 70, 65, 60, 55}, null, 3900, new String[]{"str", "damage", "hard_to_tag"}, "epic", false, null);
		itemList[117] = new BuildItemVO(117, "item_aegis", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 0, null, "artifact", false, null);
		itemList[118] = new BuildItemVO(118, "item_recipe_shivas_guard", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[119] = new BuildItemVO(119, "item_shivas_guard", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{30}, new int[]{100}, 4700, new String[]{"int", "armor", "hard_to_tag"}, "epic", false, null);
		itemList[120] = new BuildItemVO(120, "item_recipe_bloodstone", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[121] = new BuildItemVO(121, "item_bloodstone", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5050, new String[]{"regen_health", "regen_mana", "mana_pool", "health_pool"}, "epic", false, null);
		itemList[122] = new BuildItemVO(122, "item_recipe_sphere", -1, null, -1, null, null, 1325, null, "", false, null);
		itemList[123] = new BuildItemVO(123, "item_sphere", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5175, new String[]{"regen_health", "regen_mana", "str", "agi", "int", "hard_to_tag"}, "epic", false, null);
		itemList[124] = new BuildItemVO(124, "item_recipe_vanguard", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[125] = new BuildItemVO(125, "item_vanguard", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2225, new String[]{"regen_health", "block", "health_pool"}, "epic", false, null);
		itemList[126] = new BuildItemVO(126, "item_recipe_blade_mail", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[127] = new BuildItemVO(127, "item_blade_mail", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{22.0}, new int[]{25}, 2200, new String[]{"damage", "armor", "int", "hard_to_tag"}, "epic", false, null);
		itemList[128] = new BuildItemVO(128, "item_recipe_soul_booster", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[129] = new BuildItemVO(129, "item_soul_booster", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 3300, new String[]{"regen_health", "regen_mana", "health_pool", "mana_pool"}, "epic", false, null);
		itemList[130] = new BuildItemVO(130, "item_recipe_hood_of_defiance", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[131] = new BuildItemVO(131, "item_hood_of_defiance", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2125, new String[]{"regen_health", "magic_resist"}, "epic", false, null);
		itemList[132] = new BuildItemVO(132, "item_recipe_rapier", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[133] = new BuildItemVO(133, "item_rapier", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 6200, new String[]{"damage"}, "epic", false, null);
		itemList[134] = new BuildItemVO(134, "item_recipe_monkey_king_bar", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[135] = new BuildItemVO(135, "item_monkey_king_bar", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5400, new String[]{"damage", "attack_speed", "hard_to_tag"}, "epic", false, null);
		itemList[136] = new BuildItemVO(136, "item_recipe_radiance", -1, null, -1, null, null, 1350, null, "", false, null);
		itemList[137] = new BuildItemVO(137, "item_radiance", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_TOGGLE.behaviourValue, null, -1, null, null, 5150, new String[]{"damage"}, "epic", false, null);
		itemList[138] = new BuildItemVO(138, "item_recipe_butterfly", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[139] = new BuildItemVO(139, "item_butterfly", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 6000, new String[]{"agi", "damage", "evasion", "attack_speed"}, "epic", false, null);
		itemList[140] = new BuildItemVO(140, "item_recipe_greater_crit", -1, null, -1, null, null, 1200, null, "", false, null);
		itemList[141] = new BuildItemVO(141, "item_greater_crit", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5750, new String[]{"damage", "crit"}, "epic", false, null);
		itemList[142] = new BuildItemVO(142, "item_recipe_basher", -1, null, -1, null, null, 1000, null, "", false, new String[]{"npc_dota_hero_spirit_breaker", "npc_dota_hero_faceless_void", "npc_dota_hero_slardar"});
		itemList[143] = new BuildItemVO(143, "item_basher", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, new double[]{2.0}, null, 2950, new String[]{"damage", "str", "hard_to_tag"}, "epic", false, null);
		itemList[144] = new BuildItemVO(144, "item_recipe_bfury", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[145] = new BuildItemVO(145, "item_bfury", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 4350, new String[]{"damage", "health_regen", "mana_regen", "hard_to_tag"}, "epic", false, null);
		itemList[146] = new BuildItemVO(146, "item_recipe_manta", -1, null, -1, null, null, 650, null, "", false, null);
		itemList[147] = new BuildItemVO(147, "item_manta", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, 0.0, new double[]{50.0}, new int[]{165}, 4900, new String[]{"agi", "str", "int", "attack_speed", "move_speed", "hard_to_tag"}, "epic", false, null);
		itemList[148] = new BuildItemVO(148, "item_recipe_lesser_crit", -1, null, -1, null, null, 500, null, "", false, null);
		itemList[149] = new BuildItemVO(149, "item_lesser_crit", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2150, new String[]{"damage", "crit"}, "epic", false, null);
		itemList[150] = new BuildItemVO(150, "item_recipe_armlet", -1, null, -1, null, null, 700, null, "", false, null);
		itemList[151] = new BuildItemVO(151, "item_armlet", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_TOGGLE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{5.0}, null, 2600, new String[]{"damage", "attack_speed", "armor", "regen_health", "hard_to_tag"}, "epic", false, null);
		itemList[183] = new BuildItemVO(183, "item_recipe_invis_sword", -1, null, -1, null, null, 1000, null, "", false, null);
		itemList[152] = new BuildItemVO(152, "item_invis_sword", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{18.0}, new int[]{75}, 3300, new String[]{"damage", "attack_speed", "movespeed", "hard_to_tag"}, "epic", false, null);
		itemList[153] = new BuildItemVO(153, "item_recipe_sange_and_yasha", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[154] = new BuildItemVO(154, "item_sange_and_yasha", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 4300, new String[]{"damage", "str", "agi", "attack_speed", "unique"}, "artifact", false, null);
		itemList[155] = new BuildItemVO(155, "item_recipe_satanic", -1, null, -1, null, null, 1100, null, "", false, null);
		itemList[156] = new BuildItemVO(156, "item_satanic", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{35.0}, null, 6150, new String[]{"damage", "str", "armor", "unique", "hard_to_tag"}, "artifact", false, null);
		itemList[157] = new BuildItemVO(157, "item_recipe_mjollnir", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[158] = new BuildItemVO(158, "item_mjollnir", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600}, 0.0, new double[]{35.0}, new int[]{50}, 5400, new String[]{"damage", "attack_speed", "unique"}, "artifact", false, null);
		itemList[159] = new BuildItemVO(159, "item_recipe_skadi", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[160] = new BuildItemVO(160, "item_skadi", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 5850, new String[]{"agi", "str", "int", "hard_to_tag", "mana_pool", "health_pool", "unique"}, "artifact", false, null);
		itemList[161] = new BuildItemVO(161, "item_recipe_sange", -1, null, -1, null, null, 700, null, "", false, null);
		itemList[162] = new BuildItemVO(162, "item_sange", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2150, new String[]{"damage", "str", "unique"}, "artifact", false, null);
		itemList[163] = new BuildItemVO(163, "item_recipe_helm_of_the_dominator", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[164] = new BuildItemVO(164, "item_helm_of_the_dominator", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{700}, 0.0, new double[]{300.0}, new int[]{75}, 1850, new String[]{"damage", "armor", "unique", "hard_to_tag"}, "artifact", false, null);
		itemList[165] = new BuildItemVO(165, "item_recipe_maelstrom", -1, null, -1, null, null, 600, null, "", false, null);
		itemList[166] = new BuildItemVO(166, "item_maelstrom", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2700, new String[]{"damage", "attack_speed", "unique"}, "artifact", false, null);
		itemList[167] = new BuildItemVO(167, "item_recipe_desolator", -1, null, -1, null, null, 1200, null, "", false, null);
		itemList[168] = new BuildItemVO(168, "item_desolator", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 4400, new String[]{"damage", "unique"}, "artifact", false, null);
		itemList[169] = new BuildItemVO(169, "item_recipe_yasha", -1, null, -1, null, null, 700, null, "", false, null);
		itemList[170] = new BuildItemVO(170, "item_yasha", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 2150, new String[]{"agi", "attack_speed", "move_speed"}, "artifact", false, null);
		itemList[171] = new BuildItemVO(171, "item_recipe_mask_of_madness", -1, null, -1, null, null, 1000, null, "", false, null);
		itemList[172] = new BuildItemVO(172, "item_mask_of_madness", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL.behaviourValue, null, -1, new double[]{25.0}, new int[]{25}, 1900, new String[]{"unique", "hard_to_tag"}, "artifact", false, null);
		itemList[173] = new BuildItemVO(173, "item_recipe_diffusal_blade", -1, null, -1, null, null, 850, null, "", false, null);
		itemList[195] = new BuildItemVO(195, "item_recipe_diffusal_blade_2", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[174] = new BuildItemVO(174, "item_diffusal_blade", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600}, 0.0, new double[]{12.0}, new int[]{0}, 3300, new String[]{"agi", "int", "unique", "hard_to_tag"}, "artifact", false, null);
		itemList[196] = new BuildItemVO(196, "item_diffusal_blade", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{600}, 0.0, new double[]{12.0}, new int[]{0}, 3300, new String[]{"agi", "int", "unique", "hard_to_tag"}, "artifact", false, null);
		itemList[175] = new BuildItemVO(175, "item_recipe_ethereal_blade", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{700}, 0.0, new double[]{30.0}, new int[]{50}, 0, null, "epic", false, null);
		itemList[177] = new BuildItemVO(177, "item_recipe_soul_ring", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue, null, -1, new double[]{25.0}, new int[]{0}, 125, null, "common", false, null);
		itemList[179] = new BuildItemVO(179, "item_recipe_arcane_boots", -1, null, -1, null, null, 0, null, "", false, null);
		itemList[180] = new BuildItemVO(180, "item_arcane_boots", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{45.0}, new int[]{25}, 1500, new String[]{"move_speed", "boost_mana", "mana_pool"}, "rare", false, null);
		itemList[181] = new BuildItemVO(181, "item_orb_of_venom", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_PASSIVE.behaviourValue, null, -1, null, null, 450, new String[]{"hard_to_tag"}, "secret_shop", true, null);
		itemList[184] = new BuildItemVO(184, "item_recipe_ancient_janggo", -1, null, -1, null, null, 750, null, "", false, null);
		itemList[185] = new BuildItemVO(185, "item_ancient_janggo", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_IMMEDIATE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{30.0}, null, 1725, new String[]{"str", "agi", "int", "damage", "move_speed", "attack_speed", "hard_to_tag"}, "rare", false, null);
		itemList[186] = new BuildItemVO(186, "item_recipe_medallion_of_courage", -1, null, -1, null, null, 200, null, "", false, null);
		itemList[187] = new BuildItemVO(187, "item_medallion_of_courage", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_UNIT_TARGET.behaviourValue, new int[]{800}, -1, new double[]{7.0}, null, 1075, new String[]{"armor", "regen_mana", "hard_to_tag"}, "rare", false, null);
		itemList[188] = new BuildItemVO(188, "item_smoke_of_deceit", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_NO_TARGET.behaviourValue, null, -1, new double[]{90.0}, null, 100, new String[]{"consumable"}, "consumable", false, null);
		itemList[189] = new BuildItemVO(189, "item_recipe_veil_of_discord", -1, null, -1, null, null, 1250, null, "", false, null);
		itemList[190] = new BuildItemVO(190, "item_veil_of_discord", BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_AOE.behaviourValue + BuildItemVO.AbilityBehavior.DOTA_ABILITY_BEHAVIOR_POINT.behaviourValue, new int[]{875}, 0.0, new double[]{30}, new int[]{75}, 3100, new String[]{"int", "armor", "regen_health", "hard_to_tag"}, "rare", false, null);

	}
	
	public BuildItemVO getItemById(int id) {
		BuildItemVO item = null;
		
		if(id < itemList.length) {
			item = itemList[id];
		}
		
		return item;
	}
}
